version: '3.3'

services:
  web:
    container_name: iglesiasshop.web
    build: ./app
    command: gunicorn IglesiasShop.wsgi:application --bind 0.0.0.0:3762
    volumes:
      - ./app:/usr/src/app
      - ./app/static:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 80:8000
    depends_on:
      - mysql
    env_file:
      - ./app/.env
    networks:
      local_network:
        ipv4_address: 172.18.22.9

  nginx:
    container_name: iglesiasshop.proxy
    build: ./nginx
    volumes:
      - ./app/static:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      local_network:
        ipv4_address: 172.18.22.22

  mysql:
    image: mysql:latest
    container_name: iglesiasshop.mysql
    volumes:
      - db_data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: 'huffman435678'
      MYSQL_DATABASE: 'db_shop'
    ports:
      - "3306:3306"
    networks:
      local_network:
        ipv4_address: 172.18.22.16

volumes:
  static_volume:
  media_volume:
  db_data:

networks:
  local_network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

